apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-config-application
  namespace: dev
data:
  application.yml: |
    server:
      port: 9296

    spring:
      application:
        name: CLOUD-CONFIG
      zipkin:
        base-url: ${SPRING_ZIPKIN_BASE_URL:http://zipkin:9411/}
      cloud:
        config:
          server:
            git:
              uri: https://github.com/LinaA041/cloud-config-server
              default-label: master
              clone-on-start: true

    eureka:
      client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
          defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://service-discovery:8761/eureka}
      instance:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${random.value}

    management:
      endpoints:
        web:
          exposure:
            include: "*"
      health:
        circuitbreakers:
          enabled: true
      endpoint:
        health:
          show-details: always

    resilience4j:
      circuitbreaker:
        instances:
          cloudConfig:
            register-health-indicator: true
            event-consumer-buffer-size: 10
            automatic-transition-from-open-to-half-open-enabled: true
            failure-rate-threshold: 50
            minimum-number-of-calls: 5
            permitted-number-of-calls-in-half-open-state: 3
            sliding-window-size: 10
            wait-duration-in-open-state: 5s
            sliding-window-type: COUNT_BASED
