apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-rotator-role
  namespace: dev #This value can be replaced or ommited 
  labels:
    app: secret-rotation
rules:
# Permisos COMPLETOS sobre Secrets (para rotación)
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
  
# Permisos para hacer rollout restart de Deployments
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "patch"]
  
# Permisos para verificar estado de Pods
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list"]

- apiGroups: ["bitnami.com"]
  resources: ["sealedsecrets"]
  verbs: ["get", "list", "create", "update", "patch"]
