apiVersion: v1
kind: Service
metadata:
  name: {{ include "proxy-client.fullname" . }}
  labels:
    {{- include "proxy-client.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "proxy-client.selectorLabels" . | nindent 4 }}
