apiVersion: v2
name: service-discovery
description: Spring Cloud Eureka Service Discovery
type: application
version: 1.0.0
appVersion: "0.1.0"
keywords:
  - eureka
  - service-discovery
  - spring-cloud