apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config
  namespace: ecommerce-microservice
  labels:
    app: cloud-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-config
  template:
  
    metadata:
      labels:
        app: cloud-config
    spec:
      serviceAccountName: microservice-sa
      containers:
      - name: cloud-config
        image: selimhorri/cloud-config-ecommerce-boot:0.1.0
        ports:
        - containerPort: 9296
        envFrom:
        - configMapRef:
            name: common-env
        